name: waves-env
channels:
  - rmg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.18.5
  - animatplot
  - numba=0.50.1
  - progressbar2
  - ffmpeg
  - ipykernel
  - matplotlib=3.2.2
